[package]
name = "zestty-napi"
version = "0.4.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", default-features = false, features = ["napi8"] }
napi-derive = "2"
zestty = { path = "../.." }
zts-fmt = { path = "../zts-fmt" }

[build-dependencies]
napi-build = "2"
