import { compile } from "@zestty/native";
import { SourceMapConsumer } from "source-map-js";
import { buildShadow, runSvelteCheck } from "./shadow.js";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import {
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
  unlinkSync,
  existsSync,
  watch,
} from "node:fs";
import { spawnSync } from "node:child_process";
import { createRequire } from "node:module";
import { sep, join, relative, resolve, dirname, basename } from "node:path";

const SKIP_DIRS = new Set([
  "node_modules",
  ".git",
  "target",
  "dist",
  "build",
  ".svelte-kit",
  ".zts-check",
]);

/** Recursively collect .zts/.ztsx/.svelte files under root. */
export function scan(root) {
  const out = { zts: [], svelte: [] };
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        if (!SKIP_DIRS.has(entry.name)) walk(join(dir, entry.name));
      } else if (/\.ztsx?$/.test(entry.name)) {
        out.zts.push(join(dir, entry.name));
      } else if (entry.name.endsWith(".svelte")) {
        out.svelte.push(join(dir, entry.name));
      }
    }
  };
  walk(root);
  return out;
}

const SVELTE_ZTS_SCRIPT =
  /<script([^>]*\blang\s*=\s*["']zts["'][^>]*)>([\s\S]*?)<\/script>/g;

export const GENERATED_MARKER_RE =
  /^\/\/ @generated by zts-check --twins from .+\n/;

/**
 * Does the committed twin import its PREAMBLE from @zestty/core (issue
 * #37), rather than carrying it inline?
 *
 * Key on a `__zts`-prefixed specifier — never on the exact specifier
 * list, and never on the module alone. Both of those have been wrong:
 *
 * - An exact list (`{ __ztsAbsurd }`) missed 0.5.0 range twins, which
 *   import `{ __ztsAbsurd, __ztsInRange }` or just `{ __ztsInRange }`.
 *   The staleness comparison then re-compiled in INLINE mode and every
 *   committed range twin read stale forever.
 * - The module alone matched ANY core import, so a user importing `Ok`
 *   under `--inline-preamble` got the mirror-image failure: their twin
 *   looked like preamble mode, the fresh compile imported instead of
 *   inlining, and the diff never matched again.
 *
 * A `__zts*` specifier is the one signal user code provably cannot forge:
 * the semantic pass rejects `__zts`-prefixed identifiers, import
 * specifiers included. Any future preamble export is covered by
 * construction, because every one of them carries the prefix.
 */
const PREAMBLE_IMPORT_RE =
  /^import \{[^}]*\b__zts\w+\b[^}]*\} from "@zestty\/core";$/m;

/**
 * Normalize a twin for staleness comparison: committed twins may carry a
 * sourceMappingURL, CRLF line endings, and/or the --twins @generated
 * header; a fresh compile has none of these.
 */
function normalizeTwin(code) {
  return code
    .replace(/\r\n/g, "\n") // CRLF checkouts must not look stale
    .replace(GENERATED_MARKER_RE, "")
    .replace(/\n?\/\/# sourceMappingURL=\S*\s*$/, "")
    .trimEnd();
}

/**
 * Plan and materialize the shadow twins for one project.
 *
 * Twins are written IN PLACE (`foo.zts` → `foo.ts`) so that extensionless
 * relative imports between modules resolve exactly as they will for
 * consumers in committed-twins mode. If a committed twin already exists:
 * - identical content (modulo sourceMappingURL) → reuse, don't touch;
 * - different content → that's a STALE TWIN, reported as an error.
 */
export function materialize(root, { svelteScriptTwins = true } = {}) {
  const { zts, svelte } = scan(root);
  const twins = []; // { twinPath, mapJson, originalPath, created, scriptOffset }
  const errors = [];

  for (const file of zts) {
    const source = readFileSync(file, "utf8");
    const twinPath = file.replace(/\.zts(x?)$/, ".ts$1");
    // A committed twin picks the preamble mode for the comparison compile:
    // twins generated with --twins import __ztsAbsurd from @zestty/core
    // (issue #37); a fresh temp twin keeps the inline helper so plain
    // checking never requires the core dependency.
    const committedRaw = existsSync(twinPath)
      ? readFileSync(twinPath, "utf8")
      : null;
    let compiled;
    try {
      compiled = compile(source, file, {
        tsx: file.endsWith(".ztsx"),
        preambleImport:
          committedRaw !== null && PREAMBLE_IMPORT_RE.test(committedRaw),
      });
    } catch (err) {
      errors.push({ file, message: String(err.message).trimEnd() });
      continue;
    }
    if (committedRaw !== null) {
      const raw = committedRaw;
      if (normalizeTwin(raw) === normalizeTwin(compiled.code)) {
        twins.push({
          twinPath,
          mapJson: compiled.map,
          originalPath: file,
          created: false,
          scriptOffset: 0,
          // A committed --twins header shifts every line by one relative
          // to the fresh sourcemap; correct tsc positions accordingly.
          lineAdjust: GENERATED_MARKER_RE.test(raw) ? 1 : 0,
        });
      } else {
        errors.push({
          file: twinPath,
          message: `stale committed twin: ${relative(root, twinPath)} does not match a fresh compile of ${relative(root, file)} — regenerate it`,
        });
      }
      continue;
    }
    writeFileSync(twinPath, compiled.code);
    twins.push({
      twinPath,
      mapJson: compiled.map,
      originalPath: file,
      created: true,
      scriptOffset: 0,
    });
  }

  for (const file of svelteScriptTwins ? svelte : []) {
    const source = readFileSync(file, "utf8");
    // ALL lang="zts" blocks (instance + context="module"), not just the first.
    let index = 0;
    for (const m of source.matchAll(SVELTE_ZTS_SCRIPT)) {
      const scriptContent = m[2];
      // Line offset of the script *content* inside the component file.
      const scriptOffset = source
        .slice(0, m.index + m[0].indexOf(">") + 1)
        .split("\n").length;
      let compiled;
      try {
        compiled = compile(scriptContent, file, { tsx: false });
      } catch (err) {
        errors.push({ file, message: String(err.message).trimEnd() });
        index += 1;
        continue;
      }
      const suffix = index === 0 ? "" : String(index);
      const twinPath = join(
        dirname(file),
        `${basename(file, ".svelte")}.svelte-script${suffix}.ts`,
      );
      index += 1;
      if (existsSync(twinPath)) {
        errors.push({
          file: twinPath,
          message: `refusing to overwrite existing file for the svelte script twin of ${relative(root, file)}`,
        });
        continue;
      }
      writeFileSync(twinPath, compiled.code);
      twins.push({
        twinPath,
        mapJson: compiled.map,
        originalPath: file,
        created: true,
        scriptOffset: scriptOffset - 1,
      });
    }
  }

  return { twins, errors };
}

function tscFromResolved(entry) {
  // typescript's exports map hides bin/tsc from require.resolve (TS 7+),
  // so resolve the package entry point and walk up to the package root.
  let dir = dirname(entry);
  while (basename(dir) !== "typescript") {
    const parent = dirname(dir);
    if (parent === dir) throw new Error("typescript package root not found");
    dir = parent;
  }
  return join(dir, "bin", "tsc");
}

function findTsc(root) {
  try {
    const require = createRequire(join(root, "package.json"));
    return tscFromResolved(require.resolve("typescript"));
  } catch {
    // Fall back to this package's own tree (repo-local dev).
    const require2 = createRequire(import.meta.url);
    return tscFromResolved(require2.resolve("typescript"));
  }
}

const TSC_DIAG = /^(.+?)\((\d+),(\d+)\): (error TS\d+: [\s\S]*)$/;

/**
 * Run tsc over the project (or the twin files when there's no tsconfig)
 * and remap diagnostics that land inside twins back to their zts origins.
 */
export function runCheck(root, twins) {
  const tsc = findTsc(root);
  // --listFiles: every twin MUST appear in tsc's program, or a .zts outside
  // the tsconfig's include silently escapes the gate (false-green CI).
  const args = existsSync(join(root, "tsconfig.json"))
    ? ["-p", root, "--noEmit", "--pretty", "false", "--listFiles"]
    : [
        "--noEmit",
        "--strict",
        "--target",
        "es2022",
        "--module",
        "esnext",
        "--moduleResolution",
        "bundler",
        "--jsx",
        "preserve",
        "--pretty",
        "false",
        "--listFiles",
        ...twins.map((t) => t.twinPath),
      ];

  let stdout = "";
  let failed = false;
  try {
    stdout = execFileSync(process.execPath, [tsc, ...args], {
      encoding: "utf8",
      cwd: root,
    });
  } catch (err) {
    failed = true;
    stdout = `${err.stdout ?? ""}${err.stderr ?? ""}`;
  }

  const byTwin = new Map(twins.map((t) => [resolve(root, t.twinPath), t]));
  const consumers = new Map(); // twinPath -> SourceMapConsumer (built once)
  const consumerFor = (twin) => {
    let c = consumers.get(twin.twinPath);
    if (!c) {
      c = new SourceMapConsumer(JSON.parse(twin.mapJson));
      consumers.set(twin.twinPath, c);
    }
    return c;
  };

  const seenInProgram = new Set();
  const diagnostics = [];
  for (const line of stdout.split("\n")) {
    const trimmed = line.trimEnd();
    // --listFiles lines are bare absolute paths; consume them silently.
    const asPath = resolve(root, trimmed);
    if (byTwin.has(asPath) && !TSC_DIAG.test(trimmed)) {
      seenInProgram.add(asPath);
      continue;
    }
    if (/^\//.test(trimmed) && !TSC_DIAG.test(trimmed) && existsSync(trimmed)) {
      continue; // some other program file listing
    }
    const m = TSC_DIAG.exec(trimmed);
    if (!m) {
      if (trimmed.trim()) diagnostics.push({ raw: trimmed });
      continue;
    }
    const [, file, lineNo, colNo, message] = m;
    const abs = resolve(root, file);
    const twin = byTwin.get(abs);
    if (!twin) {
      diagnostics.push({ raw: trimmed });
      continue;
    }
    const orig = consumerFor(twin).originalPositionFor({
      line: Number(lineNo) - (twin.lineAdjust ?? 0),
      column: Number(colNo) - 1,
    });
    if (orig.line == null) {
      diagnostics.push({ raw: trimmed });
      continue;
    }
    diagnostics.push({
      file: twin.originalPath,
      line: orig.line + twin.scriptOffset,
      column: orig.column + 1,
      message,
    });
  }

  // C1: a twin tsc never loaded means its .zts escaped the gate entirely.
  for (const t of twins) {
    if (!seenInProgram.has(resolve(root, t.twinPath))) {
      diagnostics.push({
        file: t.originalPath,
        line: 1,
        column: 1,
        message: `error TS0: not covered by the project tsconfig (its twin ${relative(root, t.twinPath)} is outside include/files) — widen the tsconfig so this file is actually checked`,
      });
    }
  }

  return { failed, diagnostics };
}

export function cleanup(twins) {
  for (const t of twins) {
    if (t.created) {
      try {
        unlinkSync(t.twinPath);
      } catch {
        // already gone — fine
      }
    }
  }
}

const MANIFEST_DIR = ".zts-check";
const MANIFEST = "created.json";

/**
 * A manifest left behind means a previous run died before cleanup (SIGKILL,
 * OOM). Its entries are twins WE created — delete them instead of adopting
 * byte-identical leftovers as committed twins (which would later surface as
 * bogus "stale committed twin" errors the user never created).
 */
const sha = (text) => createHash("sha256").update(text).digest("hex");

function recoverLeaks(root, log) {
  const manifestPath = join(root, MANIFEST_DIR, MANIFEST);
  if (!existsSync(manifestPath)) return;
  try {
    const created = JSON.parse(readFileSync(manifestPath, "utf8"));
    // v1 manifests were arrays of paths; current ones map path → hash.
    const entries = Array.isArray(created)
      ? created.map((p) => [p, null])
      : Object.entries(created);
    for (const [twin, hash] of entries) {
      if (!existsSync(twin)) continue;
      // Only delete what is still BYTE-IDENTICAL to what we wrote: a file
      // the consumer has since edited or committed as their artifact is
      // not ours to delete (issue #16).
      if (hash != null && sha(readFileSync(twin, "utf8")) !== hash) {
        log(
          `zts-check: leaving ${relative(root, twin)} alone — it changed since an interrupted run created it`,
        );
        continue;
      }
      unlinkSync(twin);
      log(
        `zts-check: removed twin leaked by an interrupted run: ${relative(root, twin)}`,
      );
    }
  } finally {
    rmSync(join(root, MANIFEST_DIR), { recursive: true, force: true });
  }
}

function writeManifest(root, twins) {
  const created = {};
  for (const t of twins) {
    if (t.created) created[t.twinPath] = sha(readFileSync(t.twinPath, "utf8"));
  }
  if (Object.keys(created).length === 0) return;
  mkdirSync(join(root, MANIFEST_DIR), { recursive: true });
  writeFileSync(join(root, MANIFEST_DIR, MANIFEST), JSON.stringify(created));
}

function removeManifest(root) {
  rmSync(join(root, MANIFEST_DIR), { recursive: true, force: true });
}

const HAS_ZTS_SCRIPT = /<script[^>]*\blang\s*=\s*["']zts["']/;

/**
 * The sourcemap committed NEXT TO a twin (issue #45): consumed by
 * typescript-zestty-plugin to remap go-to-definition from the generated
 * .ts back into the .zts. Committed artifacts must be machine-independent
 * and diff-quiet, so sources become the sibling basename and the embedded
 * sourcesContent is dropped (the .zts sits right next to the map). The
 * leading ";" shifts every generated line down one, accounting for the
 * @generated header the twin carries but the fresh compile did not.
 */
function twinMapJson(compiled, sourcePath, twinPath) {
  const map = JSON.parse(compiled.map);
  map.file = basename(twinPath);
  map.sources = [basename(sourcePath)];
  delete map.sourcesContent;
  map.mappings = `;${map.mappings}`;
  return JSON.stringify(map);
}

/**
 * `--twins`: the committed-twins workflow. Regenerates every module twin
 * IN PLACE (create or overwrite — staleness is not an error here, it's
 * the job), never deletes anything, marks each file with an @generated
 * header, and reports ORPHANS: marker-carrying twins whose `.zts` source
 * is gone. Consumers commit the output and run plain `zts-check` in CI.
 */
export function generateTwins(
  root,
  { log = console.error, preambleImport = true } = {},
) {
  root = resolve(root);
  if (!existsSync(root)) {
    log(`zts-check: no such directory: ${root}`);
    return 2;
  }
  const { zts } = scan(root);
  let errorCount = 0;
  const wanted = new Set();
  for (const file of zts) {
    let compiled;
    try {
      compiled = compile(readFileSync(file, "utf8"), file, {
        tsx: file.endsWith(".ztsx"),
        // Committed twins import the runtime preamble from @zestty/core
        // (issue #37) so per-file boilerplate stays out of diffs;
        // --inline-preamble restores the standalone helper for consumers
        // without the core dependency.
        preambleImport,
      });
    } catch (err) {
      errorCount += 1;
      log(`${relative(root, file)}: ${String(err.message).trimEnd()}`);
      continue;
    }
    const twinPath = file.replace(/\.zts(x?)$/, ".ts$1");
    wanted.add(twinPath);
    const header = `// @generated by zts-check --twins from ${basename(file)}\n`;
    const mapName = `${basename(twinPath)}.map`;
    writeFileSync(
      twinPath,
      `${header}${compiled.code}//# sourceMappingURL=${mapName}\n`,
    );
    writeFileSync(
      join(dirname(twinPath), mapName),
      twinMapJson(compiled, file, twinPath),
    );
    log(`zts-check: wrote ${relative(root, twinPath)}`);
  }

  for (const orphan of findGeneratedOrphans(root, wanted)) {
    errorCount += 1;
    log(
      `zts-check: ORPHAN twin ${relative(root, orphan)} — its .zts source is gone; delete the twin or restore the source`,
    );
  }
  return errorCount === 0 ? 0 : 1;
}

/**
 * `zts-check --twins --watch [--exec <cmd>]` (issue #35): regenerate twins
 * continuously while authoring `.zts`/`.ztsx`.
 *
 * - Watches ONLY zts sources (extension whitelist), so the `.ts` twins
 *   `--twins` writes back can never re-trigger the watcher (no loop), and
 *   whatever `--exec` writes (e.g. `svelte-kit sync` output) is inert too.
 * - Changes are debounced and coalesced into one regeneration pass.
 * - `exec` runs after each successful regeneration (the downstream sync
 *   hook); its failure is reported but does not stop the watch.
 *
 * Returns `{ close() }`. Requires Node 20+ (recursive fs.watch on Linux).
 */
export function watchTwins(
  root,
  {
    log = console.error,
    exec = null,
    preambleImport = true,
    debounceMs = 100,
  } = {},
) {
  root = resolve(root);
  if (!existsSync(root)) {
    log(`zts-check: no such directory: ${root}`);
    return null;
  }

  const isSource = (name) => /\.zts(x?)$/.test(name);
  const inSkippedDir = (rel) =>
    rel.split(sep).some((segment) => SKIP_DIRS.has(segment));

  const runOnce = () => {
    const code = generateTwins(root, { log, preambleImport });
    if (code === 0 && exec) {
      const r = spawnSync(exec, {
        shell: true,
        cwd: root,
        stdio: ["ignore", "inherit", "inherit"],
      });
      if (r.status !== 0) {
        log(`zts-check: --exec failed (exit ${r.status ?? "signal"}): ${exec}`);
      }
    }
    return code;
  };

  runOnce();
  log(`zts-check: watching ${root} for .zts/.ztsx changes`);

  let timer = null;
  const watcher = watch(root, { recursive: true }, (_event, filename) => {
    if (!filename || !isSource(filename) || inSkippedDir(filename)) {
      return;
    }
    clearTimeout(timer);
    timer = setTimeout(() => {
      timer = null;
      runOnce();
    }, debounceMs);
  });

  return {
    close() {
      clearTimeout(timer);
      watcher.close();
    },
  };
}

/** Marker-carrying .ts/.tsx files whose source no longer exists. */
function findGeneratedOrphans(root, wanted) {
  const orphans = [];
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const p = join(dir, entry.name);
      if (entry.isDirectory()) {
        if (!SKIP_DIRS.has(entry.name)) walk(p);
      } else if (/\.tsx?$/.test(entry.name) && !wanted.has(p)) {
        const head = readFileSync(p, "utf8").slice(0, 200);
        if (GENERATED_MARKER_RE.test(head)) orphans.push(p);
      }
    }
  };
  walk(root);
  return orphans;
}

/** Full run. Returns an exit code. */
export function ztsCheck(
  root,
  { keep = false, svelte = true, log = console.error } = {},
) {
  root = resolve(root);
  if (!existsSync(root)) {
    log(`zts-check: no such directory: ${root}`);
    return 2;
  }

  recoverLeaks(root, log);

  // Template checking: when svelte-check is available, components are
  // checked WHOLE (template bindings included) over a shadow tree, and the
  // script-twin path is skipped for them to avoid double-reporting.
  const ztsComponents = svelte
    ? scan(root).svelte.filter((f) =>
        HAS_ZTS_SCRIPT.test(readFileSync(f, "utf8")),
      )
    : [];
  const useShadow = ztsComponents.length > 0;

  let twins = [];
  let errorCount = 0;

  // Ctrl-C / CI cancellation must not leave twins in the tree.
  const onSignal = (signal) => {
    cleanup(twins);
    removeManifest(root);
    process.exit(signal === "SIGINT" ? 130 : 143);
  };
  const SIGNALS = ["SIGINT", "SIGTERM", "SIGHUP"];
  for (const sig of SIGNALS) process.on(sig, onSignal);

  try {
    const materialized = materialize(root, { svelteScriptTwins: !useShadow });
    twins = materialized.twins;
    writeManifest(root, twins);

    for (const e of materialized.errors) {
      errorCount += 1;
      log(`${relative(root, e.file)}: ${e.message}`);
    }

    if (twins.length === 0 && !useShadow) {
      if (errorCount === 0) log("zts-check: nothing to check");
      return errorCount === 0 ? 0 : 1;
    }

    if (twins.length > 0) {
      const { failed, diagnostics } = runCheck(root, twins);
      for (const d of diagnostics) {
        if (d.raw != null) {
          errorCount += /error TS\d+/.test(d.raw) ? 1 : 0;
          log(d.raw);
        } else {
          errorCount += 1;
          log(`${relative(root, d.file)}(${d.line},${d.column}): ${d.message}`);
        }
      }
      if (failed && errorCount === 0) {
        // tsc failed without parseable diagnostics — surface that loudly.
        errorCount += 1;
        log("zts-check: tsc exited non-zero without diagnostics");
      }
    }

    if (useShadow) {
      const shadowDir = join(root, MANIFEST_DIR, "shadow");
      // Shadow compile errors duplicate the module-twin errors already
      // reported above; components-only errors surface via svelte-check.
      const { components } = buildShadow(root, shadowDir);
      const svelteDiags = runSvelteCheck(root, shadowDir, components);
      if (svelteDiags == null) {
        // Script twins were skipped in anticipation — fall back so the
        // scripts are still checked, and say what was NOT checked.
        log(
          'zts-check: svelte-check not found — template bindings in lang="zts" components were NOT checked (scripts still are; install svelte-check for full coverage)',
        );
        const fallback = materialize(root, { svelteScriptTwins: true });
        const scriptTwins = fallback.twins.filter((t) =>
          t.originalPath.endsWith(".svelte"),
        );
        twins.push(...scriptTwins);
        const { diagnostics } = runCheck(root, scriptTwins);
        for (const d of diagnostics) {
          if (d.raw != null) {
            errorCount += /error TS\d+/.test(d.raw) ? 1 : 0;
            log(d.raw);
          } else {
            errorCount += 1;
            log(
              `${relative(root, d.file)}(${d.line},${d.column}): ${d.message}`,
            );
          }
        }
      } else {
        for (const d of svelteDiags) {
          errorCount += 1;
          log(`${relative(root, d.file)}(${d.line},${d.column}): ${d.message}`);
        }
      }
      if (!keep) rmSync(shadowDir, { recursive: true, force: true });
    }
  } finally {
    for (const sig of SIGNALS) process.off(sig, onSignal);
    if (!keep) {
      cleanup(twins);
      removeManifest(root);
    }
  }

  if (errorCount === 0) {
    log("zts-check: clean");
  }
  return errorCount === 0 ? 0 : 1;
}
