// Regression tests for the adoption-round issues (#15, #16, #18).
import { test } from "node:test";
import assert from "node:assert/strict";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { ztsCheck, generateTwins } from "@zestty/check";

const FIXTURES = join(dirname(fileURLToPath(import.meta.url)), "fixtures");

// Committed twins import the runtime preamble from @zestty/core (issue
// #37); a tmp consumer dir needs the package resolvable like a real
// consumer's node_modules.
const CORE_PKG = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "core",
);
function linkCore(dir) {
  mkdirSync(join(dir, "node_modules", "@zestty"), { recursive: true });
  symlinkSync(CORE_PKG, join(dir, "node_modules", "@zestty", "core"));
}

test("#15: SvelteKit-style tsconfig extends ./.svelte-kit works in the shadow", () => {
  const lines = [];
  const code = ztsCheck(join(FIXTURES, "sveltekit-extends"), {
    log: (l) => lines.push(l),
  });
  assert.equal(code, 0, lines.join("\n"));
  assert.match(lines.join("\n"), /clean/);
});

test("#16: a modified/committed twin listed in a stale manifest is NOT deleted", () => {
  const dir = mkdtempSync(join(tmpdir(), "zts-manifest-"));
  try {
    writeFileSync(join(dir, "a.zts"), "export const n: number = 1;\n");
    // Interrupted-run state: twin + hash manifest.
    let code = ztsCheck(dir, { keep: true, log: () => {} });
    assert.equal(code, 0);
    // Consumer commits/edits the twin (content differs from the hash).
    writeFileSync(
      join(dir, "a.ts"),
      "// mine now\nexport const n: number = 1;\n",
    );
    const lines = [];
    code = ztsCheck(dir, { log: (l) => lines.push(l) });
    assert.ok(
      existsSync(join(dir, "a.ts")),
      "modified twin must NOT be deleted",
    );
    assert.match(lines.join("\n"), /leaving .* alone/);
    // And the modified twin is then correctly flagged stale.
    assert.equal(code, 1);
    assert.match(lines.join("\n"), /stale committed twin/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("#16b: --twins regenerates in place, marks output, reports orphans", () => {
  const dir = mkdtempSync(join(tmpdir(), "zts-twins-"));
  try {
    writeFileSync(
      join(dir, "a.zts"),
      "export const n: number = if (true as boolean) { 1 } else { 2 };\n",
    );
    let lines = [];
    let code = generateTwins(dir, { log: (l) => lines.push(l) });
    assert.equal(code, 0, lines.join("\n"));
    const twin = readFileSync(join(dir, "a.ts"), "utf8");
    assert.match(twin, /^\/\/ @generated by zts-check --twins from a\.zts\n/);

    // The marker-carrying committed twin passes a plain check (not stale),
    // even with the extra header line.
    lines = [];
    code = ztsCheck(dir, { log: (l) => lines.push(l) });
    assert.equal(code, 0, lines.join("\n"));

    // Stale source content → --twins overwrites without complaint.
    writeFileSync(
      join(dir, "a.zts"),
      "export const n: number = if (false as boolean) { 3 } else { 4 };\n",
    );
    code = generateTwins(dir, { log: () => {} });
    assert.equal(code, 0);
    assert.match(readFileSync(join(dir, "a.ts"), "utf8"), /3/);

    // Orphan: source deleted, marked twin remains → loud error.
    unlinkSync(join(dir, "a.zts"));
    lines = [];
    code = generateTwins(dir, { log: (l) => lines.push(l) });
    assert.equal(code, 1);
    assert.match(lines.join("\n"), /ORPHAN twin/);
    assert.ok(existsSync(join(dir, "a.ts")), "orphan is reported, not deleted");
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("#16b: committed marker twin still maps diagnostics to correct lines", () => {
  const dir = mkdtempSync(join(tmpdir(), "zts-twinmap-"));
  try {
    const src = `type T = { kind: "K"; v: number } | { kind: "L"; w: number };
declare const t: T;

export const r = match (t) {
  K { v } => v,
};
`;
    writeFileSync(join(dir, "m.zts"), src);
    linkCore(dir);
    generateTwins(dir, { log: () => {} });
    const lines = [];
    const code = ztsCheck(dir, { log: (l) => lines.push(l) });
    assert.equal(code, 1);
    const out = lines.join("\n");
    assert.match(out, /m\.zts\(\d+,\d+\): error TS2345/);
    const line = Number(out.match(/m\.zts\((\d+),/)[1]);
    // The header line in the committed twin must not shift the mapping:
    // the diagnostic still lands on the `match` line.
    assert.match(src.split("\n")[line - 1], /match/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
