// Regression tests for the adoption-round issues (#15, #16, #18).
import { test } from "node:test";
import assert from "node:assert/strict";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { ztsCheck, generateTwins } from "@zestty/check";

const FIXTURES = join(dirname(fileURLToPath(import.meta.url)), "fixtures");

// Committed twins import the runtime preamble from @zestty/core (issue
// #37); a tmp consumer dir needs the package resolvable like a real
// consumer's node_modules.
const CORE_PKG = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "core",
);
function linkCore(dir) {
  mkdirSync(join(dir, "node_modules", "@zestty"), { recursive: true });
  symlinkSync(CORE_PKG, join(dir, "node_modules", "@zestty", "core"));
}

test("#15: SvelteKit-style tsconfig extends ./.svelte-kit works in the shadow", () => {
  const lines = [];
  const code = ztsCheck(join(FIXTURES, "sveltekit-extends"), {
    log: (l) => lines.push(l),
  });
  assert.equal(code, 0, lines.join("\n"));
  assert.match(lines.join("\n"), /clean/);
});

test("#16: a modified/committed twin listed in a stale manifest is NOT deleted", () => {
  const dir = mkdtempSync(join(tmpdir(), "zts-manifest-"));
  try {
    writeFileSync(join(dir, "a.zts"), "export const n: number = 1;\n");
    // Interrupted-run state: twin + hash manifest.
    let code = ztsCheck(dir, { keep: true, log: () => {} });
    assert.equal(code, 0);
    // Consumer commits/edits the twin (content differs from the hash).
    writeFileSync(
      join(dir, "a.ts"),
      "// mine now\nexport const n: number = 1;\n",
    );
    const lines = [];
    code = ztsCheck(dir, { log: (l) => lines.push(l) });
    assert.ok(
      existsSync(join(dir, "a.ts")),
      "modified twin must NOT be deleted",
    );
    assert.match(lines.join("\n"), /leaving .* alone/);
    // And the modified twin is then correctly flagged stale.
    assert.equal(code, 1);
    assert.match(lines.join("\n"), /stale committed twin/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("#16b: --twins regenerates in place, marks output, reports orphans", () => {
  const dir = mkdtempSync(join(tmpdir(), "zts-twins-"));
  try {
    writeFileSync(
      join(dir, "a.zts"),
      "export const n: number = if (true as boolean) { 1 } else { 2 };\n",
    );
    let lines = [];
    let code = generateTwins(dir, { log: (l) => lines.push(l) });
    assert.equal(code, 0, lines.join("\n"));
    const twin = readFileSync(join(dir, "a.ts"), "utf8");
    assert.match(twin, /^\/\/ @generated by zts-check --twins from a\.zts\n/);

    // The marker-carrying committed twin passes a plain check (not stale),
    // even with the extra header line.
    lines = [];
    code = ztsCheck(dir, { log: (l) => lines.push(l) });
    assert.equal(code, 0, lines.join("\n"));

    // Stale source content → --twins overwrites without complaint.
    writeFileSync(
      join(dir, "a.zts"),
      "export const n: number = if (false as boolean) { 3 } else { 4 };\n",
    );
    code = generateTwins(dir, { log: () => {} });
    assert.equal(code, 0);
    assert.match(readFileSync(join(dir, "a.ts"), "utf8"), /3/);

    // Orphan: source deleted, marked twin remains → loud error.
    unlinkSync(join(dir, "a.zts"));
    lines = [];
    code = generateTwins(dir, { log: (l) => lines.push(l) });
    assert.equal(code, 1);
    assert.match(lines.join("\n"), /ORPHAN twin/);
    assert.ok(existsSync(join(dir, "a.ts")), "orphan is reported, not deleted");
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("#45: --twins emits a committed sourcemap next to each twin", () => {
  const dir = mkdtempSync(join(tmpdir(), "zts-twinsmap-"));
  try {
    writeFileSync(
      join(dir, "a.zts"),
      "export const n: number = if (true as boolean) { 1 } else { 2 };\n",
    );
    const code = generateTwins(dir, { log: () => {} });
    assert.equal(code, 0);
    const twin = readFileSync(join(dir, "a.ts"), "utf8");
    assert.match(twin, /\/\/# sourceMappingURL=a\.ts\.map\n$/);
    const map = JSON.parse(readFileSync(join(dir, "a.ts.map"), "utf8"));
    // Committed artifacts are machine-independent and diff-quiet:
    // sibling-relative source, no embedded sourcesContent.
    assert.deepEqual(map.sources, ["a.zts"]);
    assert.equal(map.file, "a.ts");
    assert.equal(map.sourcesContent, undefined);
    // Shifted for the @generated header line the fresh compile lacks.
    assert.match(map.mappings, /^;/);
    // And the map-carrying twin still passes a plain check (not stale).
    const lines = [];
    assert.equal(
      ztsCheck(dir, { log: (l) => lines.push(l) }),
      0,
      lines.join("\n"),
    );
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("#16b: committed marker twin still maps diagnostics to correct lines", () => {
  const dir = mkdtempSync(join(tmpdir(), "zts-twinmap-"));
  try {
    const src = `type T = { kind: "K"; v: number } | { kind: "L"; w: number };
declare const t: T;

export const r = match (t) {
  K { v } => v,
};
`;
    writeFileSync(join(dir, "m.zts"), src);
    linkCore(dir);
    generateTwins(dir, { log: () => {} });
    const lines = [];
    const code = ztsCheck(dir, { log: (l) => lines.push(l) });
    assert.equal(code, 1);
    const out = lines.join("\n");
    assert.match(out, /m\.zts\(\d+,\d+\): error TS2345/);
    const line = Number(out.match(/m\.zts\((\d+),/)[1]);
    // The header line in the committed twin must not shift the mapping:
    // the diagnostic still lands on the `match` line.
    assert.match(src.split("\n")[line - 1], /match/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("#73: a committed twin with a range arm is not permanently stale", () => {
  // The staleness comparison re-compiles the source and diffs it against
  // the committed twin, choosing preamble mode from what the twin already
  // imports. That detection used to match the exact specifier list
  // `{ __ztsAbsurd }`; a range arm adds `__ztsInRange`, so the twin looked
  // like inline mode, the fresh compile inlined the preamble, and the diff
  // never matched again — every committed range twin read stale forever.
  const dir = mkdtempSync(join(tmpdir(), "zts-rangetwin-"));
  try {
    const src = `type Code = 200 | 404 | 500;
declare const c: Code;

export const label = match (c) {
  200..=299 => "ok",
  400..=499 => "client",
  500..=599 => "server",
};
`;
    writeFileSync(join(dir, "r.zts"), src);
    linkCore(dir);
    generateTwins(dir, { log: () => {} });

    const twin = readFileSync(join(dir, "r.ts"), "utf8");
    assert.match(
      twin,
      /^import \{ __ztsAbsurd, __ztsInRange \} from "@zestty\/core";$/m,
      "a range twin must import both preamble helpers",
    );

    // The freshly generated twin must read CLEAN, not stale.
    const lines = [];
    const code = ztsCheck(dir, { log: (l) => lines.push(l) });
    assert.equal(code, 0, lines.join("\n"));
    assert.doesNotMatch(lines.join("\n"), /stale committed twin/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("#73: a wildcard-terminated range twin imports only __ztsInRange", () => {
  // The other end of the same bug: with a `_` arm there is no keystone at
  // all, so the specifier list is `{ __ztsInRange }` — nothing like the
  // pattern the old detection looked for.
  const dir = mkdtempSync(join(tmpdir(), "zts-rangetwin-w-"));
  try {
    writeFileSync(
      join(dir, "w.zts"),
      `export const digit = (n: number): string =>
  match (n) {
    0..=9 => "digit",
    _ => "other",
  };
`,
    );
    linkCore(dir);
    generateTwins(dir, { log: () => {} });
    const twin = readFileSync(join(dir, "w.ts"), "utf8");
    assert.match(twin, /^import \{ __ztsInRange \} from "@zestty\/core";$/m);
    assert.doesNotMatch(twin, /__ztsAbsurd/);

    const lines = [];
    assert.equal(
      ztsCheck(dir, { log: (l) => lines.push(l) }),
      0,
      lines.join("\n"),
    );
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("#73: an inline-preamble twin that imports from core stays clean", () => {
  // The mirror image of the range-twin bug. Keying preamble detection on
  // the MODULE matched any @zestty/core import, so a consumer who uses
  // `Ok`/`Err` in a project committed with inline preambles looked like
  // preamble mode: the fresh compile imported the helper instead of
  // inlining it, and the twin read stale with no way back.
  //
  // A `__zts*` SPECIFIER is the signal user code cannot forge — the
  // semantic pass rejects `__zts`-prefixed identifiers, import specifiers
  // included.
  const dir = mkdtempSync(join(tmpdir(), "zts-inlinecore-"));
  try {
    writeFileSync(
      join(dir, "u.zts"),
      `import { Ok } from "@zestty/core";
type Code = 200 | 404;
declare const c: Code;

export const r = Ok(match (c) {
  200 => "ok",
  404 => "missing",
});
`,
    );
    linkCore(dir);
    generateTwins(dir, { preambleImport: false, log: () => {} });

    const twin = readFileSync(join(dir, "u.ts"), "utf8");
    assert.match(twin, /^import \{ Ok \} from "@zestty\/core";$/m);
    assert.match(
      twin,
      /function __ztsAbsurd\(/,
      "inline mode must carry the helper, not import it",
    );
    assert.doesNotMatch(twin, /^import \{[^}]*__zts/m);

    const lines = [];
    const code = ztsCheck(dir, { log: (l) => lines.push(l) });
    assert.equal(code, 0, lines.join("\n"));
    assert.doesNotMatch(lines.join("\n"), /stale committed twin/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
