// typescript-zestty-plugin — TS Language Service plugin (issue #45).
//
// In committed-twins mode every import resolves to the generated `.ts`
// twin, so go-to-definition from any consumer (`.ts`, `.svelte`) is
// answered by tsserver and lands in generated code; the zestty
// language-server only serves `.zts` buffers and is never in that
// resolution path. This plugin intercepts the definition-shaped queries
// and, when the target file carries the `@generated by zts-check --twins
// from <name>.zts` header, remaps the span to the sibling `.zts`:
// primarily through the `.ts.map` sourcemap `zts-check --twins` emits
// next to the twin, falling back to a whole-word symbol search in the
// `.zts` when no map is present.
//
// Loaded by tsserver via `require`, so this file is CommonJS and must
// not depend on the TypeScript API surface (the `typescript` module the
// host passes in is unused — remapping is pure text/sourcemap work).

"use strict";

const fs = require("node:fs");
const { dirname, join } = require("node:path");
const { SourceMapConsumer } = require("source-map-js");

// Must match GENERATED_MARKER_RE in @zestty/check — the header is the
// contract that marks a file as a twin and names its source.
const GENERATED_MARKER_RE =
  /^\/\/ @generated by zts-check --twins from (.+?)\r?\n/;

/** 0-based line/character of a UTF-16 offset in `text`. */
function offsetToLineCol(text, offset) {
  let line = 0;
  let lineStart = 0;
  for (let i = 0; i < offset && i < text.length; i++) {
    if (text.charCodeAt(i) === 10) {
      line += 1;
      lineStart = i + 1;
    }
  }
  return { line, character: offset - lineStart };
}

/** UTF-16 offset of a 0-based line/character in `text` (clamped). */
function lineColToOffset(text, line, character) {
  let offset = 0;
  for (let l = 0; l < line; l++) {
    const next = text.indexOf("\n", offset);
    if (next === -1) return Math.min(offset + character, text.length);
    offset = next + 1;
  }
  return Math.min(offset + Math.max(0, character), text.length);
}

const WORD_CHAR = /[A-Za-z0-9_$]/;

/** First whole-word occurrence of `name` in `text`, or -1. */
function wholeWordIndex(text, name) {
  if (!name) return -1;
  let from = 0;
  for (;;) {
    const i = text.indexOf(name, from);
    if (i === -1) return -1;
    const before = i === 0 ? "" : text[i - 1];
    const after = text[i + name.length] ?? "";
    if (!WORD_CHAR.test(before) && !WORD_CHAR.test(after)) return i;
    from = i + 1;
  }
}

function init() {
  function create(info) {
    const ls = info.languageService;
    const host = info.languageServiceHost;
    const log = (message) => {
      info.project?.projectService?.logger?.info(
        `[typescript-zestty-plugin] ${message}`,
      );
    };

    const readFile = (path) => {
      if (host && typeof host.readFile === "function") {
        return host.readFile(path);
      }
      try {
        return fs.readFileSync(path, "utf8");
      } catch {
        return undefined;
      }
    };
    const fileExists = (path) =>
      host && typeof host.fileExists === "function"
        ? host.fileExists(path)
        : fs.existsSync(path);

    /**
     * Sourcemap position of the twin-local `textSpan.start`, as a
     * 0-based offset into `ztsText`, or null when there is no usable
     * map. The committed map is already shifted for the @generated
     * header, so twin coordinates feed it directly.
     */
    const mapThroughSourcemap = (def, twinText, ztsText) => {
      const mapText = readFile(`${def.fileName}.map`);
      if (mapText == null) return null;
      try {
        const consumer = new SourceMapConsumer(JSON.parse(mapText));
        const { line, character } = offsetToLineCol(
          twinText,
          def.textSpan.start,
        );
        const orig = consumer.originalPositionFor({
          line: line + 1,
          column: character,
        });
        if (orig.line == null) return null;
        return lineColToOffset(ztsText, orig.line - 1, orig.column ?? 0);
      } catch (err) {
        log(`unusable sourcemap for ${def.fileName}: ${err}`);
        return null;
      }
    };

    /** Remap one DefinitionInfo-shaped entry, or return it unchanged. */
    const remapDefinition = (def) => {
      if (!def || !def.fileName || !def.textSpan) return def;
      if (!/\.tsx?$/.test(def.fileName)) return def;
      const twinText = readFile(def.fileName);
      if (twinText == null) return def;
      const marker = GENERATED_MARKER_RE.exec(twinText);
      if (!marker) return def;
      const ztsPath = join(dirname(def.fileName), marker[1].trim());
      if (!fileExists(ztsPath)) {
        log(`twin ${def.fileName} names a missing source ${ztsPath}`);
        return def;
      }
      const ztsText = readFile(ztsPath);
      if (ztsText == null) return def;

      let start = mapThroughSourcemap(def, twinText, ztsText);
      if (start == null) start = wholeWordIndex(ztsText, def.name);
      if (start == null || start < 0) return def;

      // The map lands on the token start; trust the symbol's own length
      // when the target text confirms it, else keep a conservative span.
      const length =
        def.name && ztsText.startsWith(def.name, start)
          ? def.name.length
          : Math.min(def.textSpan.length, ztsText.length - start);
      return {
        ...def,
        fileName: ztsPath,
        textSpan: { start, length },
        // A twin-local context range has no meaning in the .zts.
        contextSpan: undefined,
      };
    };

    const proxy = Object.create(null);
    for (const key of Object.keys(ls)) {
      const member = ls[key];
      proxy[key] =
        typeof member === "function"
          ? (...args) => member.apply(ls, args)
          : member;
    }

    proxy.getDefinitionAndBoundSpan = (fileName, position, ...rest) => {
      const result = ls.getDefinitionAndBoundSpan(fileName, position, ...rest);
      if (!result || !result.definitions) return result;
      return {
        ...result,
        definitions: result.definitions.map(remapDefinition),
      };
    };

    for (const method of [
      "getDefinitionAtPosition",
      "getTypeDefinitionAtPosition",
      "getImplementationAtPosition",
    ]) {
      if (typeof ls[method] !== "function") continue;
      proxy[method] = (fileName, position, ...rest) => {
        const result = ls[method](fileName, position, ...rest);
        return Array.isArray(result) ? result.map(remapDefinition) : result;
      };
    }

    log("activated");
    return proxy;
  }

  return { create };
}

module.exports = init;
